dependencies:
  - base == 4.*
  - base-compat >= 0.8
  - process
  - fsnotify
  - time
  - wai
  - warp
  - http-types
  - system-filepath >= 0.4.13.2
  - stm
  - text
  - network
  - ansi-terminal
  - directory
  - http-client
  - bytestring

ghc-options: -Wall

library:
  source-dirs: 
    - src
    - doctest/ghci-wrapper/src/

executables:
  autospec:
    main: driver/Main.hs
    dependencies:
      - autospec

  autospec-web:
    main: driver/Web.hs
    dependencies:
      - autospec

  autospec-client:
    main: driver/Client.hs
    dependencies:
      - autospec

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - doctest/ghci-wrapper/src/
    dependencies:
      - autospec
      - hspec == 2.*
      - hspec-wai
      - mockery
      - silently
      - interpolate
